### ISSUE TITLE
Value annotation is incomplete

### ISSUE THREAD

**Issue by zzl221000** [helospark/light-di#3]
required=false only be used for String does not support other types
String[] not support

**Comment by helospark** [comment]
Thank you @zzl221000 for reporting this, it is indeed a bug.

What do you expect the value to be in case of String[] array, when it cannot be resolved?
Originally for String it was an empty String, however after some thought, I think it would make more sense if these values were simply not set by LightDi (if default value is explicitly required, the ':' can always be used to define defaults).

**Comment by zzl221000** [comment]
Thank you @helospark for replying.
I did not describe my question clearly.
Does the value annotation support array?

**Comment by helospark** [comment]
@zzl221000 Yes, `@Value` annotation generally supports arrays. Value elements are separated by comma.
For example you can see an example in the integration tests:
[ComponentWithCollectionValue](https://github.com/helospark/light-di/blob/22126f336333140e16c3907640f4e07b5afc0d71/src/test/java/com/helospark/lightdi/it/testcontext1/ComponentWithCollectionValue.java#L11)
[ContextLoadIT](https://github.com/helospark/light-di/blob/849f9750d6e070ef9d05940bf0e95c28c14b4eb1/src/test/java/com/helospark/lightdi/it/ContextLoadIT.java#L172)

However as you pointed out, when `@Value` annotation has required=false and it is missing value to resolve it indeed fails with an exception.
Seems like a modification is required so in that case it just leaves the field as `null`.

**Comment by helospark** [comment]
Released in 0.0.6
